# ---------------------------------------------------------------
# This program shows if a verifycode from client is matching
# for a secret key on Webserver.
# Written by Yingli Zhao, February 2022
# ---------------------------------------------------------------
import pyotp


def google_verify_result(secret_key, verifycode):
    """ verify if a user is a valid user
    :param secret_key: generated by authMethode, mapping to a QRcode
    :param verifycode: Time based password for NOW
    """
    t = pyotp.TOTP(secret_key)
    # Generate a TOTP object for a certain secret key
    result = t.verify(verifycode)
    # compare the given verifycode and generated One Time Password for t，return True in case matching
    msg = result if result is True else False
    return msg
